import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBer from "./components/NavBer";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast";
 
 


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hire-Loop - App",
  description: "Generated by Hire-Loop - app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">

        <NavBer/>
        <main>
        {children}
        </main>
        <Footer />
        <Toaster />
        </body>
    </html>
  );
}
